// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "bon_dance_prologue_anim_cells.inc.c"

struct Animation anim_bon_dance_prologue_title[] = {
    /* 000 */ { bon_dance_prologue_cel000, 4 },
    /* 001 */ { bon_dance_prologue_cel001, 20 },
    /* 002 */ { bon_dance_prologue_cel002, 10 },
    /* 003 */ { bon_dance_prologue_cel003, 6 },
    /* 004 */ { bon_dance_prologue_cel002, 30 },
    /* 005 */ END_ANIMATION,
};

