// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel sneaky_spirits_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x000f
};

AnimationCel sneaky_spirits_prologue_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x40f1, 0x81b8, 0x0080
};

AnimationCel sneaky_spirits_prologue_cel002[] = {
    /* Len */ 2,
    /* 000 */ 0x40f1, 0x81b8, 0x0080,
    /* 001 */ 0x40f1, 0x81d3, 0x0084
};

AnimationCel sneaky_spirits_prologue_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x40f1, 0x81d3, 0x0084,
    /* 001 */ 0x40f1, 0x81b8, 0x0080,
    /* 002 */ 0x40f1, 0x81f1, 0x0089
};

AnimationCel sneaky_spirits_prologue_cel004[] = {
    /* Len */ 4,
    /* 000 */ 0x4003, 0x81d0, 0x00ce,
    /* 001 */ 0x40f1, 0x81d3, 0x0084,
    /* 002 */ 0x40f1, 0x81b8, 0x0080,
    /* 003 */ 0x40f1, 0x81f1, 0x0089
};

AnimationCel sneaky_spirits_prologue_cel005[] = {
    /* Len */ 5,
    /* 000 */ 0x4003, 0x81d0, 0x00ce,
    /* 001 */ 0x0003, 0x41e8, 0x00d2,
    /* 002 */ 0x40f1, 0x81d3, 0x0084,
    /* 003 */ 0x40f1, 0x81b8, 0x0080,
    /* 004 */ 0x40f1, 0x81f1, 0x0089
};

AnimationCel sneaky_spirits_prologue_cel006[] = {
    /* Len */ 6,
    /* 000 */ 0x0003, 0x41e8, 0x00d2,
    /* 001 */ 0x4003, 0x81d0, 0x00ce,
    /* 002 */ 0x4003, 0x81f7, 0x00d6,
    /* 003 */ 0x40f1, 0x81d3, 0x0084,
    /* 004 */ 0x40f1, 0x81b8, 0x0080,
    /* 005 */ 0x40f1, 0x81f1, 0x0089
};

