// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel sneaky_spirits_2_prologue_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x000f
};

AnimationCel sneaky_spirits_2_prologue_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x40f0, 0x81b8, 0x0080
};

AnimationCel sneaky_spirits_2_prologue_cel002[] = {
    /* Len */ 2,
    /* 000 */ 0x40f0, 0x81d3, 0x0084,
    /* 001 */ 0x40f0, 0x81b8, 0x0080
};

AnimationCel sneaky_spirits_2_prologue_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x40f0, 0x81d3, 0x0084,
    /* 001 */ 0x40f0, 0x81b8, 0x0080,
    /* 002 */ 0x40f0, 0x81f1, 0x0089
};

AnimationCel sneaky_spirits_2_prologue_cel004[] = {
    /* Len */ 4,
    /* 000 */ 0x4001, 0x81cf, 0x00ce,
    /* 001 */ 0x40f0, 0x81f1, 0x0089,
    /* 002 */ 0x40f0, 0x81b8, 0x0080,
    /* 003 */ 0x40f0, 0x81d3, 0x0084
};

AnimationCel sneaky_spirits_2_prologue_cel005[] = {
    /* Len */ 5,
    /* 000 */ 0x4001, 0x81e7, 0x00d2,
    /* 001 */ 0x4001, 0x81cf, 0x00ce,
    /* 002 */ 0x40f0, 0x81f1, 0x0089,
    /* 003 */ 0x40f0, 0x81b8, 0x0080,
    /* 004 */ 0x40f0, 0x81d3, 0x0084
};

AnimationCel sneaky_spirits_2_prologue_cel006[] = {
    /* Len */ 6,
    /* 000 */ 0x4001, 0x81cf, 0x00ce,
    /* 001 */ 0x4001, 0x81e7, 0x00d2,
    /* 002 */ 0x4001, 0x81f6, 0x00d6,
    /* 003 */ 0x40f0, 0x81f1, 0x0089,
    /* 004 */ 0x40f0, 0x81b8, 0x0080,
    /* 005 */ 0x40f0, 0x81d3, 0x0084
};

AnimationCel sneaky_spirits_2_prologue_cel007[] = {
    /* Len */ 7,
    /* 000 */ 0x8000, 0x8012, 0x0000,
    /* 001 */ 0x4001, 0x81f6, 0x00d6,
    /* 002 */ 0x4001, 0x81e7, 0x00d2,
    /* 003 */ 0x4001, 0x81cf, 0x00ce,
    /* 004 */ 0x40f0, 0x81f1, 0x0089,
    /* 005 */ 0x40f0, 0x81b8, 0x0080,
    /* 006 */ 0x40f0, 0x81d3, 0x0084
};

