// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel medal_corner_menus_cel000[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x0016, 0x801c
};

AnimationCel medal_corner_menus_cel001[] = {
    /* Len */ 1,
    /* 000 */ 0x00f8, 0x41ea, 0x8003
};

AnimationCel medal_corner_menus_cel002[] = {
    /* Len */ 1,
    /* 000 */ 0x00f8, 0x41e9, 0x8003
};

AnimationCel medal_corner_menus_cel003[] = {
    /* Len */ 1,
    /* 000 */ 0x00f8, 0x41e8, 0x8003
};

AnimationCel medal_corner_menus_cel004[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x800a
};

AnimationCel medal_corner_menus_cel005[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x800b
};

AnimationCel medal_corner_menus_cel006[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x8009
};

AnimationCel medal_corner_menus_cel007[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x800e
};

AnimationCel medal_corner_menus_cel008[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x800c
};

AnimationCel medal_corner_menus_cel009[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x800d
};

AnimationCel medal_corner_menus_cel010[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x8008
};

AnimationCel medal_corner_menus_cel011[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x8005
};

AnimationCel medal_corner_menus_cel012[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x8006
};

AnimationCel medal_corner_menus_cel013[] = {
    /* Len */ 1,
    /* 000 */ 0x80f8, 0x0016, 0x8007
};

AnimationCel medal_corner_menus_cel014[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x801d
};

AnimationCel medal_corner_menus_cel015[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x801b
};

AnimationCel medal_corner_menus_cel016[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x8019
};

AnimationCel medal_corner_menus_cel017[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x801a
};

AnimationCel medal_corner_menus_cel018[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x8030
};

AnimationCel medal_corner_menus_cel019[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x8031
};

AnimationCel medal_corner_menus_cel020[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x802f
};

AnimationCel medal_corner_menus_cel021[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x801e
};

AnimationCel medal_corner_menus_cel022[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x801f
};

AnimationCel medal_corner_menus_cel023[] = {
    /* Len */ 1,
    /* 000 */ 0x00fc, 0x01fc, 0x8018
};

AnimationCel medal_corner_menus_cel024[] = {
    /* Len */ 6,
    /* 000 */ 0x400c, 0x41e4, 0x8032,
    /* 001 */ 0x400c, 0x4004, 0x8036,
    /* 002 */ 0x4014, 0x000e, 0x803e,
    /* 003 */ 0x4014, 0x41ee, 0x803a,
    /* 004 */ 0x80ec, 0x81f6, 0x8000,
    /* 005 */ 0x00ec, 0x41fe, 0x8001
};

AnimationCel medal_corner_menus_cel025[] = {
    /* Len */ 5,
    /* 000 */ 0x4008, 0x41dc, 0x800f,
    /* 001 */ 0x4008, 0x41fc, 0x8013,
    /* 002 */ 0x0008, 0x001c, 0x8017,
    /* 003 */ 0x80e4, 0x81f4, 0x8000,
    /* 004 */ 0x80e4, 0x4004, 0x8002
};

