// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "marching_orders_prologue_anim_cells.inc.c"

struct Animation anim_marching_orders_prologue_title[] = {
    /* 000 */ { marching_orders_prologue_cel000, 40 },
    /* 001 */ { marching_orders_prologue_cel001, 20 },
    /* 002 */ { marching_orders_prologue_cel002, 20 },
    /* 003 */ { marching_orders_prologue_cel003, 20 },
    /* 004 */ { marching_orders_prologue_cel004, 20 },
    /* 005 */ { marching_orders_prologue_cel005, 20 },
    /* 006 */ { marching_orders_prologue_cel006, 20 },
    /* 007 */ { marching_orders_prologue_cel007, 100 },
    /* 008 */ END_ANIMATION,
};

