// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

AnimationCel ninja_bodyguard_prologue_cel000[] = {
    /* Len */ 3,
    /* 000 */ 0x00c8, 0xc1e6, 0x1000,
    /* 001 */ 0x00a6, 0xc1cf, 0x100a,
    /* 002 */ 0x00a6, 0xc00f, 0x1012
};

AnimationCel ninja_bodyguard_prologue_cel001[] = {
    /* Len */ 3,
    /* 000 */ 0x00a6, 0xc00f, 0x2012,
    /* 001 */ 0x00a6, 0xc1cf, 0x200a,
    /* 002 */ 0x00c8, 0xc1e6, 0x2000
};

AnimationCel ninja_bodyguard_prologue_cel002[] = {
    /* Len */ 3,
    /* 000 */ 0x00a6, 0xc00f, 0x3012,
    /* 001 */ 0x00a6, 0xc1cf, 0x300a,
    /* 002 */ 0x00c8, 0xc1e6, 0x3000
};

AnimationCel ninja_bodyguard_prologue_cel003[] = {
    /* Len */ 3,
    /* 000 */ 0x00a6, 0xc00f, 0x4012,
    /* 001 */ 0x00a6, 0xc1cf, 0x400a,
    /* 002 */ 0x00c8, 0xc1e6, 0x4000
};

AnimationCel ninja_bodyguard_prologue_cel004[] = {
    /* Len */ 3,
    /* 000 */ 0x00a6, 0xc00f, 0x5012,
    /* 001 */ 0x00a6, 0xc1cf, 0x500a,
    /* 002 */ 0x00c8, 0xc1e6, 0x5000
};

AnimationCel ninja_bodyguard_prologue_cel005[] = {
    /* Len */ 3,
    /* 000 */ 0x00a6, 0xc00f, 0x6012,
    /* 001 */ 0x00a6, 0xc1cf, 0x600a,
    /* 002 */ 0x00c8, 0xc1e6, 0x6000
};

