.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Long 2) - Script Entry Point

script script_drum_lesson_long_2_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_long_2_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_long_2, script_drum_lesson_long_2_entry



.section .rodata
@ Drum Lesson (Long 2) - Data

text D_08062d98
    .ascii "Escucha el patr‡in, y\n"
    .ascii "rep‡etelo cuando est‡Qs listo.\n"
    .ascii "Repetir‡Q el patr‡in si\n"
    .asciz "dejas de tocar."
endtext


script D_08062df0
    spawn_cue CUE_SNARE_L
    rest 24
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_08062ebc
    spawn_cue CUE_KICK_R
    rest 21
return


text D_08062ee0
    .ascii "\n"
    .ascii "Sub‡cmosle bien fuerte!\n"
    .ascii "Pongamos un crash al inicio y\n"
    .asciz "un platillo al final! Venga!\n"
endtext


script D_08062f10
    spawn_cue CUE_SNARE_L
    rest 24
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return


script D_08062ff4
    spawn_cue CUE_KICK_R
    spawn_cue CUE_CRASH
    rest 21
return


text D_08063024
    .ascii "\n"
    .ascii "Cambiemos el bajo un poco.\n"
    .ascii "Escucha con cuidado y\n"
    .asciz "que no pare el ritmo!"
endtext


script D_08063058
    spawn_cue CUE_SNARE_L
    rest 12
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return


text D_08063184
    .ascii "Por ˆ¦ltimo, pero no menos\n"
    .ascii "importante, otro pulso de bombo.\n"
    .ascii "Ya casi podemos irnos a casa.\n"
    .asciz "Dale, que es mi cumple!\n"
endtext


script D_080631c4
    spawn_cue CUE_SNARE_L
    rest 12
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 12
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return



.section .script.main
@ Drum Lesson (Long 2) - Tables

struct D_08a42d28
    .word D_08062ebc
    .word D_08062df0
    .word s_hakushu_solo_seqData
    .word D_08062d98
endstruct

struct D_08a42d38
    .word D_08062ff4
    .word D_08062f10
    .word s_hakushu_solo_seqData
    .word D_08062ee0
endstruct

struct D_08a42d48
    .word D_08062ff4
    .word D_08063058
    .word s_warai_little_seqData
    .word D_08063024
endstruct

struct D_08a42d58
    .word D_08062ff4
    .word D_080631c4
    .word s_warai_seqData
    .word D_08063184
endstruct



@ Drum Lesson (Long 2) - Main Script

script script_drum_lesson_long_2_main
    set_tempo 120
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    dms_event02 TRUE
    run drum_lesson_script_import_pattern, D_08a42d28
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42d38
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42d48
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a42d58
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
