.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Short 4) - Script Entry Point

script script_drum_lesson_short_4_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_short_4_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_short_4, script_drum_lesson_short_4_entry



.section .rodata
@ Drum Lesson (Short 4) - Data

text D_0805f560
    .ascii "Escucha el patr‡in, y\n"
    .ascii "rep‡etelo cuando est‡Qs listo.\n"
    .ascii "Repetir‡Q el patr‡in si\n"
    .asciz "dejas de tocar."
endtext


script D_0805f5b8
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


script D_0805f624
    spawn_cue CUE_KICK_R
    rest 21
return


text D_0805f648
    .ascii "\n"
    .ascii "Puse otro pulso de bombo!\n"
    .asciz "Apenas comenzamos!\n"
endtext


script D_0805f670
    spawn_cue CUE_KICK_R
    rest 18
    spawn_cue CUE_KICK_R
    rest 3
return

text D_0805f6ac
    .ascii "\n"
    .ascii "Hay una nueva adici‡in al\n"
    .ascii "set, que ser‡c?\n"
    .asciz "Pulsa Arriba en el ‡O !"
endtext


script D_0805f6ec
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_HIHAT
    rest 6
    spawn_cue CUE_KICK_R
    rest 3
return


text D_0805f740
    .ascii "\n"
    .ascii "Pongamos algo de S‡encopa\n"
    .ascii "al final. La verdad, esto\n"
    .asciz "es algo t‡Qcnico!\n"
endtext


script D_0805f770
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_0805f7f4
    .ascii "Ahora un pulso de\n"
    .ascii " tom, justo al final!\n"
    .ascii "Recuerdas d‡inde est‡c?\n"
    .asciz "( ‡O )"
endtext


script D_0805f840
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_TOM
    rest 12
return


text D_0805f8dc
    .ascii "\n"
    .ascii "Sorpresa! Un pulso de\n"
    .ascii "caja aqu‡e en medio!\n"
    .asciz "Comienza a agarrar forma!\n"
endtext


script D_0805f918
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_TOM
    rest 12
return


text D_0805f9cc
    .ascii "\n"
    .ascii "Ese fue nuestro primer platillo\n"
    .ascii "c‡embal, el hi-hat!\n"
    .asciz "Puedes darle con Arriba en el ‡O.\n"
endtext


text D_0805fa10
    .ascii "\n"
    .ascii "Arriba en el ‡O puede ser o\n"
    .ascii "el hi-hat o el redoble, depende\n"
    .asciz "de que set de bater‡ea estemos usando.\n"
endtext


text D_0805fa60
    .ascii "\n"
    .ascii "Ahora s‡e, v‡cmonos\n"
    .asciz "con la clase!"
endtext



.section .script.main
@ Drum Lesson (Short 4) - Tables

struct D_08a41230
    .word D_0805f624
    .word D_0805f5b8
    .word s_hakushu_solo_seqData
    .word D_0805f560
endstruct

struct D_08a41240
    .word D_0805f670
    .word D_0805f5b8
    .word s_hakushu_solo_seqData
    .word D_0805f648
endstruct

struct D_08a41250
    .word D_0805f6ec
    .word D_0805f5b8
    .word s_warai_little_seqData
    .word D_0805f6ac
endstruct

struct D_08a41260
    .word D_0805f6ec
    .word D_0805f770
    .word s_warai_seqData
    .word D_0805f740
endstruct

struct D_08a41270
    .word D_0805f6ec
    .word D_0805f840
    .word s_kansei_solo_seqData
    .word D_0805f7f4
endstruct

struct D_08a41280
    .word D_0805f6ec
    .word D_0805f918
    .word s_kansei_seqData
    .word D_0805f8dc
endstruct



@ Drum Lesson (Short 4) - Main Script

script script_drum_lesson_short_4_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    dms_event02 TRUE
    run drum_lesson_script_import_pattern, D_08a41230
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41240
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41250
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_dialogue_text D_0805f9cc
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_0805fa10
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_0805fa60
    rest 12
    dms_event15
    dms_event16
    rest 12
    run drum_lesson_script_import_pattern, D_08a41260
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41270
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a41280
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
