.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Basic 2) - Script Entry Point

script script_drum_lesson_basic_2_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_basic_2_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_basic_2, script_drum_lesson_basic_2_entry



.section .rodata
@ Drum Lesson (Basic 2) - Data

text D_08061998
    .ascii "Escucha el patr‡in, y\n"
    .ascii "rep‡etelo cuando est‡Qs listo.\n"
    .ascii "Repetir‡Q el patr‡in si\n"
    .asciz "dejas de tocar."
endtext


script D_080619f0
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
return


script D_08061a44
    spawn_cue CUE_KICK_R
    rest 21
return


text D_08061a68
    .ascii "\n"
    .ascii "Cambie un pulso de bombo\n"
    .ascii "por uno de caja.\n"
    .asciz "Notas la diferencia?"
endtext


script D_08061a90
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061ae4
    .ascii "\n"
    .ascii "Ahora, otro cambio!\n"
    .asciz "Crees poder?\n"
endtext


script D_08061b10
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061b64
    .ascii "\n"
    .ascii "Agreguemos un pulso\n"
    .ascii "m‡cs de bombo!\n"
    .asciz "Yo s‡Q que puedes!"
endtext


script D_08061b94
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061c00
    .ascii "Escuchas el pulso de bombo?\n"
    .ascii "Alternar entre\n"
    .ascii "‡N y Abajo en el ‡O\n"
    .asciz "lo hace m‡cs f‡ccil!"
endtext


script D_08061c2c
    spawn_cue CUE_SNARE_L
    rest 24
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 24
return


text D_08061cb0
    .ascii "Te traje un regalo!\n"
    .ascii "Es un pulso nuevo!\n"
    .ascii "Espero lo disfrutes,\n"
    .asciz "que ya casi terminamos!"
endtext


script D_08061cdc
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_KICK_R
    rest 9
return


text D_08061d18
    .ascii "\n"
    .ascii "En esta clase,\n"
    .ascii "usaremos dos tambores:\n"
    .asciz "el bombo y la caja.\n"
endtext


text D_08061d70
    .ascii "\n"
    .ascii "Dale a el bombo con ‡N\n"
    .asciz "o pulsando Abajo en el ‡O!\n"
endtext


text D_08061dbc
    .ascii "Si tomaste la ˆ¦ltima clase\n"
    .ascii "sabras que puedes\n"
    .ascii "darle a ‡M o a la Izquierda en el ‡O\n"
    .asciz "para tocar la caja."
endtext


text D_08061e04
    .ascii "\n"
    .ascii "Manten todo eso en mente\n"
    .ascii "mientras toques este set!\n"
    .ascii "Comencemos, lenta, mente...\n"
endtext



.section .script.main
@ Drum Lesson (Basic 2) - Tables

struct D_08a42504
    .word D_08061a44
    .word D_080619f0
    .word s_hakushu_solo_seqData
    .word D_08061998
endstruct

struct D_08a42514
    .word D_08061a44
    .word D_08061a90
    .word s_hakushu_solo_seqData
    .word D_08061a68
endstruct

struct D_08a42524
    .word D_08061a44
    .word D_08061b10
    .word s_warai_little_seqData
    .word D_08061ae4
endstruct

struct D_08a42534
    .word D_08061a44
    .word D_08061b94
    .word s_warai_seqData
    .word D_08061b64
endstruct

struct D_08a42544
    .word D_08061a44
    .word D_08061c2c
    .word s_kansei_solo_seqData
    .word D_08061c00
endstruct

struct D_08a42554
    .word D_08061cdc
    .word D_08061c2c
    .word s_kansei_seqData
    .word D_08061cb0
endstruct



@ Drum Lesson (Basic 2) - Main Script

script script_drum_lesson_basic_2_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    rest 24
    dms_event02 TRUE
    rest 24
    dms_set_dialogue_text D_08061d18
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061d70
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061dbc
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061e04
    rest 12
    dms_event15
    dms_event16
    rest 12
    rest 24
    run drum_lesson_script_import_pattern, D_08a42504
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42514
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42524
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42534
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42544
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a42554
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
