.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Basic 1) - Script Entry Point

script script_drum_lesson_basic_1_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_basic_1_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_basic_1, script_drum_lesson_basic_1_entry



.section .rodata
@ Drum Lesson (Basic 1) - Data

text D_080613e4
    .ascii "Escucha el patr‡in, y\n"
    .ascii "rep‡etelo cuando est‡Qs listo.\n"
    .ascii "Repetir‡Q el patr‡in si\n"
    .asciz "dejas de tocar."
endtext


script D_0806143c
    spawn_cue CUE_SNARE_R
    rest 24
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_SNARE_R
    rest 24
return


script D_080614a8
    spawn_cue CUE_SNARE_R
    rest 21
return


text D_080614cc
    .ascii "\n"
    .ascii "Ten un nuevo pulso!\n"
    .ascii "Alterna entre el ‡O y el ‡M \n"
    .asciz "para los tiempos r‡cpidos.\n"
endtext


script D_080614f4
    spawn_cue CUE_SNARE_R
    rest 24
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_SNARE_R
    rest 24
return


text D_08061578
    .ascii "\n"
    .ascii "Vamos con otro pulso!\n"
    .ascii "A ver si lo encuentras!\n"
    .asciz "Tˆ¦ puedes, lo s‡Q.\n"
endtext


script D_080615a8
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 9
return


text D_080615e4
    .ascii "\n"
    .ascii "Y ahora, otro\n"
    .ascii "toque justo al final!\n"
    .asciz "Crees que puedes?\n"
endtext


script D_08061614
    spawn_cue CUE_SNARE_R
    rest 24
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_SNARE_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return


script D_080616b0
    spawn_cue CUE_SNARE_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_SNARE_R
    rest 9
return


text D_08061704
    .ascii "Bienvenido a Toca Bater‡ea!\n"
    .ascii "Empecemos simple,\n"
    .ascii "solo con la caja.\n"
    .asciz "Luego pondremos m‡cs acci‡in.\n"
endtext


text D_08061740
    .ascii "\n"
    .ascii "Dale a la caja con ‡M o\n"
    .asciz "d‡cndole a la derecha en el ‡O!\n"
endtext


text D_0806178c
    .ascii "No te rindas si te\n"
    .ascii "cuesta al inicio. Puedes\n"
    .ascii "Intentarlo cuanto quieras.\n"
    .asciz "Ya con eso, comencemos!\n"
endtext


text D_080617bc
    .ascii "\n"
    .ascii "Eh? Las luces de arriba?\n"
    .ascii "Ah, son las luces al ritmo!\n"
    .asciz ""
endtext


text D_080617f0
    .ascii "Estas parpadean a tu ritmo:\n"
    .ascii "Izquierda, si estas apurado,\n"
    .ascii "Derecha, si estas atrasado,\n"
    .asciz "Al centro si esta correcto!"
endtext


text D_0806183c
    .ascii "Si tienes problemas con\n"
    .ascii "tu pulso, mira las luces\n"
    .asciz "para guiarte sobre tus errores."
endtext


text D_08061884
    .ascii "\n"
    .ascii "Bueno, bueno, sigamos\n"
    .asciz "con la clase!"
endtext


text D_0806189c
    .ascii "Si voy muy r‡cpido y\n"
    .ascii "te cuesta captarme,\n"
    .ascii "puedes pulsar START.\n"
    .asciz "\n"
endtext


text D_080618d8
    .ascii "\n"
    .ascii "Eso bajara el tempo.\n"
    .ascii "Asi, podras o‡erme mejor.\n"
    .asciz "Entendido?.\n"
endtext


text D_08061910
    .ascii "\n"
    .ascii "Pulsa START de nuevo\n"
    .ascii "para deshacer la velocidad.\n"
    .asciz "Ah, casi lo olvido..."
endtext


text D_08061950
    .ascii "\n"
    .ascii "La clase no puede avanzar\n"
    .ascii "en modo lento. Tendr‡cs que\n"
    .asciz "ir a la velocidad normal."
endtext


text D_08061980
    .ascii "\n"
    .asciz "Ahora, terminemos con esto!"
endtext



.section .script.main
@ Drum Lesson (Basic 1) - Tables

struct D_08a41e90
    .word D_080614a8
    .word D_0806143c
    .word s_hakushu_solo_seqData
    .word D_080613e4
endstruct

struct D_08a41ea0
    .word D_080614a8
    .word D_080614f4
    .word s_hakushu_solo_seqData
    .word D_080614cc
endstruct

struct D_08a41eb0
    .word D_080615a8
    .word D_080614f4
    .word s_warai_little_seqData
    .word D_08061578
endstruct

struct D_08a41ec0
    .word D_080615a8
    .word D_08061614
    .word s_warai_seqData
    .word D_080615e4
endstruct

struct D_08a41ed0
    .word D_080616b0
    .word D_08061614
    .word s_kansei_solo_seqData
    .word D_080614cc
endstruct



@ Drum Lesson (Basic 1) - Main Script

script script_drum_lesson_basic_1_main
    set_tempo 116
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    rest 24
    dms_event02 TRUE
    rest 24
    dms_set_dialogue_text D_08061704
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061740
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_0806178c
    rest 12
    dms_event15
    dms_event16
    rest 12
    rest 24
    run drum_lesson_script_import_pattern, D_08a41e90
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41ea0
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_dialogue_text D_080617bc
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_080617f0
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_0806183c
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061884
    rest 12
    dms_event15
    dms_event16
    rest 12
    run drum_lesson_script_import_pattern, D_08a41eb0
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a41ec0
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_dialogue_text D_0806189c
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_080618d8
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061910
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061950
    rest 12
    dms_event15
    dms_event16
    rest 12
    dms_set_dialogue_text D_08061980
    rest 12
    dms_event15
    dms_event16
    rest 12
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a41ed0
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
