.include "include/beatscript.inc"
.include "games/drum_studio/macros.inc"



.section .script.entry
@ Drum Lesson (Short 2) - Script Entry Point

script script_drum_lesson_short_2_entry
    set_tempo 124
    rest 24
    rest 24
    load_drum_lessons
    enable_play_inputs
    start_tracking_inputs
    call script_drum_lesson_short_2_main
    disable_pause_menu
    disable_play_inputs
    fade_music_out 48
    fade_screen_out 12, BLACK
    rest 24
    rest 24
stop

define_gameplay_scene scene_drum_lesson_short_2, script_drum_lesson_short_2_entry



.section .rodata
@ Drum Lesson (Short 2) - Data

text D_08061e24
    .ascii "Escucha el patr‡in, y\n"
    .ascii "rep‡etelo cuando est‡Qs listo.\n"
    .ascii "Repetir‡Q el patr‡in si\n"
    .asciz "dejas de tocar."
endtext


script D_08061e7c
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
    spawn_cue CUE_KICK_R
    rest 24
return


script D_08061ed0
    spawn_cue CUE_KICK_R
    rest 21
return


text D_08061ef4
    .ascii "\n"
    .ascii "Ahora, un contratiempo\n"
    .ascii "de caja! Intenso, no?\n"
    .asciz "Una, dos, Una, dos!"
endtext


script D_08061f24
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return


script D_08061fc0
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 9
return


text D_08061ffc
    .ascii "Vale, hagamos una locura!\n"
    .ascii "Cambiemos una nota de bajo\n"
    .ascii "un poco mas atr‡cs.\n"
    .asciz "Es pillo, pero se puede!"
endtext


script D_0806203c
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
return


text D_080620e4
    .ascii "\n"
    .ascii "Pondre otro pulso\n"
    .ascii "en ese espacio de ah‡e.\n"
    .asciz "Dale con todo!\n"
endtext


script D_08062114
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 12
return


text D_080621d4
    .ascii "\n"
    .ascii "Acabemos con esto con un redoble\n"
    .ascii "en ese segundo pulso de bombo.\n"
    .asciz "A roquear!"
endtext


script D_08062200
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 12
    spawn_cue CUE_KICK_R
    rest 12
    spawn_cue CUE_SNARE_L
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    rest 6
    spawn_cue CUE_KICK_R
    rest 6
    spawn_cue CUE_SNARE_L
    rest 12
return



.section .script.main
@ Drum Lesson (Short 2) - Tables

struct D_08a42870
    .word D_08061ed0
    .word D_08061e7c
    .word s_hakushu_solo_seqData
    .word D_08061e24
endstruct

struct D_08a42880
    .word D_08061fc0
    .word D_08061f24
    .word s_hakushu_solo_seqData
    .word D_08061ef4
endstruct

struct D_08a42890
    .word D_08061fc0
    .word D_0806203c
    .word s_warai_little_seqData
    .word D_08061ffc
endstruct

struct D_08a428a0
    .word D_08061fc0
    .word D_08062114
    .word s_warai_seqData
    .word D_080620e4
endstruct

struct D_08a428b0
    .word D_08061fc0
    .word D_08062200
    .word s_kansei_solo_seqData
    .word D_080621d4
endstruct



@ Drum Lesson (Short 2) - Main Script

script script_drum_lesson_short_2_main
    set_tempo 108
    set_music_volume 256
    stop_tracking_inputs
    dms_event08 4
    dms_event09 1
    rest 24
    dms_event02 TRUE
    run drum_lesson_script_import_pattern, D_08a42870
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42880
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a42890
    call drum_lessons_sub_08a7d7a0
    run drum_lesson_script_import_pattern, D_08a428a0
    call drum_lessons_sub_08a7d7a0
    start_tracking_inputs
    run drum_lesson_script_import_pattern, D_08a428b0
    call drum_lessons_sub_08a7d7a0
    dms_show_dialogue TRUE
    dms_set_teacher_exp TEACHER_EXP_GIVE_RANK
    dms_get_lesson_score
return

.end
