// Generated by Sofanthiel [https://github.com/shaffyswitcher/sofanthiel]

#include "global.h"
#include "graphics.h"

#include "clappy_trio_anim_cells.inc.c"

struct Animation anim_clappy_trio_test[] = {
    /* 000 */ { clappy_trio_cel000, 3 },
    /* 001 */ { clappy_trio_cel001, 3 },
    /* 002 */ { clappy_trio_cel002, 20 },
    /* 003 */ { clappy_trio_cel003, 3 },
    /* 004 */ { clappy_trio_cel004, 3 },
    /* 005 */ { clappy_trio_cel005, 20 },
    /* 006 */ { clappy_trio_cel006, 3 },
    /* 007 */ { clappy_trio_cel007, 3 },
    /* 008 */ { clappy_trio_cel008, 20 },
    /* 009 */ { clappy_trio_cel012, 1 },
    /* 010 */ { clappy_trio_cel013, 2 },
    /* 011 */ { clappy_trio_cel015, 3 },
    /* 012 */ { clappy_trio_cel016, 20 },
    /* 013 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_smirk_dupe1[] = {
    /* 000 */ { clappy_trio_cel009, 3 },
    /* 001 */ { clappy_trio_cel010, 3 },
    /* 002 */ { clappy_trio_cel011, 20 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_smirk_dupe2[] = {
    /* 000 */ { clappy_trio_cel009, 3 },
    /* 001 */ { clappy_trio_cel010, 3 },
    /* 002 */ { clappy_trio_cel011, 20 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_beat[] = {
    /* 000 */ { clappy_trio_cel000, 3 },
    /* 001 */ { clappy_trio_cel001, 3 },
    /* 002 */ { clappy_trio_cel002, 20 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_smile[] = {
    /* 000 */ { clappy_trio_cel003, 3 },
    /* 001 */ { clappy_trio_cel004, 3 },
    /* 002 */ { clappy_trio_cel005, 20 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_glare[] = {
    /* 000 */ { clappy_trio_cel006, 3 },
    /* 001 */ { clappy_trio_cel007, 3 },
    /* 002 */ { clappy_trio_cel008, 20 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_smirk[] = {
    /* 000 */ { clappy_trio_cel009, 3 },
    /* 001 */ { clappy_trio_cel010, 3 },
    /* 002 */ { clappy_trio_cel011, 20 },
    /* 003 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_clap[] = {
    /* 000 */ { clappy_trio_cel012, 1 },
    /* 001 */ { clappy_trio_cel013, 2 },
    /* 002 */ { clappy_trio_cel015, 3 },
    /* 003 */ { clappy_trio_cel016, 10 },
    /* 004 */ { clappy_trio_cel016, 10 },
    /* 005 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_player_icon[] = {
    /* 000 */ { clappy_trio_cel018, 4 },
    /* 001 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_sign[] = {
    /* 000 */ { clappy_trio_cel019, 4 },
    /* 001 */ { clappy_trio_cel020, 4 },
    /* 002 */ END_ANIMATION,
};

struct Animation anim_clappy_trio_text_box[] = {
    /* 000 */ { clappy_trio_cel021, 4 },
    /* 001 */ END_ANIMATION,
};

